export const walkingDeskLinks = {
    "key://urevo_3s": "https://amzn.to/4bE2JXR",
    "key://urevo_2s_lite": "https://amzn.to/3ROlFvN",
    "key://deerrun": "https://amzn.to/4hvQCzj",
    "key://cyberpad": "https://shareasale.com/r.cfm?b=2635321&u=4069700&m=159466&urllink=www%2Eurevo%2Ecom%2Fcollections%2Funder%2Ddesk%2Dtreadmill%2Fproducts%2Furevo%2Dcyberpad%2Dfor%2Dhome%2Dtreadmill&afftrack=blog",
    "key://urevo_strol": "https://amzn.to/4aCme3Z",
    "key://urevo_e5": "https://amzn.to/4jsteob",
    "key://urevo_e4": "https://amzn.to/3xxWWV9",
    "key://urevo_e3": "https://amzn.to/3zxMhLt",
    "key://mat": "https://amzn.to/3WrW0v5",
    "key://lube": "https://amzn.to/3E7YUPw",
    "key://flexispot": "https://amzn.to/40Kddmd",
    "key://shoes_men": "https://amzn.to/4au1fk1",
    "key://shoes_women": "https://amzn.to/3WvoJiM",
    "key://fluidstance": "https://shareasale.com/r.cfm?b=1147740&u=4069700&m=74356&urllink=&afftrack=",
    "key://slimblade": "https://amzn.to/3tIE30e",
    "key://keychron": "https://amzn.to/49INDPN",
    "key://mistel": "https://amzn.to/3U0tBue",
    "key://esd_wristband": "https://amzn.to/3Uz0XSA",
    "key://vivo": "https://amzn.to/3xCuL7C",
    "key://mountup": "https://amzn.to/3xL35O9",
    "key://gloves": "https://amzn.to/48oewbX",
}