export const id = '20240109-fitness-desk'
export const url = '/walk'
export const date = '2024-01-09'
export const updated = '2025-03-22'
export const title = "Best Walking Pads 2025"
export const pinned = true
export const affiliate = true
export const teaser = "Comparison of treadmill desk options. Under-desk walking pads, videos showing how and when to use each option, standing desks, monitor arms, and ergonomic peripherals. Walking pads compared include [placeholder], and more."
export const jsx = true;