export const title = 'Salary'
export const episode = 6
export const mergeEpisode = 36
export const mla = true
export const created = "2018-07-19"
export const guid = "fac919cc-45b9-4eda-9cff-3ba3821a6c7b"
export const libsynEpisode = 16622978
export const teaser = "Salary based on location, gender, age, tech... from O'Reilly. Get full survey report: [2017 Data Science Salary Survey](https://www.oreilly.com/data/free/2017-data-science-salary-survey.csp)"
export const empty = true