version: "3.7"
services:
  vid2aud:
    build: .
    container_name: vid2aud
    ports:
      - 9000:8080
    #entrypoint: /bin/bash
    #stdin_open: true
    volumes:
      - ~/.aws:/root/.aws
      - ./task:/var/task

# docker-compose up -d vid2aud
# curl -XPOST "http://localhost:9000/2015-03-31/functions/function/invocations" -d '{"url": "https://www.youtube.com/watch?v=Oi1r3e8y2jg"}'