export const title = 'Code AI. Cursor, Cline, Roo, Aider, Copilot, Windsurf'
export const episode = 22
export const mergeEpisode = 55
export const mla = true
export const created = '2025-02-09'
export const updated = "2025-04-11"
export const guid = 35212505
export const libsynEpisode = 35212505
export const teaser = "Compares popular AI coding plugins and IDEs: Cursor, Cline, Roo Code, Aider, Github Copilot, Windsurf. AI is transforming coding through a \"vibe coding\": leveraging LLMs with tool-calling to assist in code generation and testing. Many AI-driven IDEs and plugins are evolving rapidly, offering diverse agentic capabilities, each with unique strengths."