export const title = 'Storage: HDF, Pickle, Postgres'
export const episode = 3
export const mergeEpisode = 33
export const mla = true
export const created = "2018-05-24"
export const guid = "e038d5ef-46e7-4d1c-be4f-4835536679d5"
export const libsynEpisode = 16622999
export const teaser = "Comparison of different data storage options when working with your ML models. You'll ingest your dataset (CSV, TSV, JSON API, ..) via Pandas. Then you munge the data / Pandas, convert to Numpy & send to your model. Model saves intermediate steps as Numpy->HDF. Publish results of your model's predictions (whether for use in app/website, or for researchers, etc) in a SQL database or CSV."
export const empty = true